### PR TITLE
revise error handling, also some control flow adjustments

### PR DESCRIPTION
**Pull request by hannesm**
see https://github.com/mirage/mirage-dev/pull/166

### CODE REVIEW

**Comment by mato** [comment]
@hannesm This doesn't build for me with `mirage-dev` either, where is the `V1.Network` supposed to come from? Perhaps make this change without removing the `stats` types, which I gather is what you're trying to get out of `V1.Network`?

**Comment by hannesm** [comment]
@mato this branch is supposed to work with my network-error branch of mirage-dev (https://github.com/hannesm/mirage-dev/tree/network-error) (see also https://github.com/mirage/mirage/pull/615).  The goal was a) centralise error definition and pretty printer b) use result instead of polymorphic variants, and only c) see what else we can unify. `stats` (and useful functions, defined in mirage-net-xen) are excellent candidates.

The pretty printer and Network implementation are provided by mirage-types (and mirage-types.lwt for lwt stuff).  I'd first wait for more comments on https://github.com/mirage/mirage-dev/pull/166 before merging

**Comment by hannesm** [comment]
and there is no implementation of `V1.Network`, but there is `M_pp` (https://github.com/mirage/mirage/pull/615/files#diff-89c249e40b9ec2e680b59376182e9eb4), which provides a `pp_network_error`.  This module dance is done to avoid having to provide a V1.ml (which would be a lot of copy & pasting of types).

**Comment by yomimono** [comment]
@mato any objections to merging this?

**Comment by mato** [comment]
@yomimono Last I checked the dependencies for this were not merged in mirage/mirage-types, see @hannesm comments above.

**Comment by yomimono** [comment]
@mato I'm merging them now, any _other_ objections?

**Comment by mato** [comment]
@yomimono Nope, LGTM.

**Comment by yomimono** [comment]
Thanks @mato!

**Pull request merged**
