### PR TITLE
test 4.06 as well

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by mato** [comment]
You missed 4.05 here, might want to add it?

**Comment by hannesm** [comment]
done.  I'm not sure how many OCaml versions we should attempt to support at once... for most of mirage I added `>= 4.04.2` constraints - maybe a viable strategy for solo5 related things as well?

**Comment by mato** [comment]
@hannesm Thanks.

> I'm not sure how many OCaml versions we should attempt to support at once... for most of mirage I added >= 4.04.2 constraints - maybe a viable strategy for solo5 related things as well?

Dunno, I've yet to get around to reading the relevant thread on the list. I agree that we should trim down the tested and supported versions, and if we do that then also add the relevant constraints and document it somewhere. If nothing else it will not waste CI (and thus developer) time testing on old compilers no one is using.

**Comment by hannesm** [comment]
@mato exactly.  I'm mostly concerned about developer hours, and don't see an advantage of supporting more than two major OCaml versions.  Mirage-xen used to need 4.04.2 until recently (now 4.05 works as well).

but agreed, we should discuss this (a) on the mailing list and (b) write it on mirage.io somewhere prominent so people will see it.

**Pull request merged**
