### PR TITLE
adjustments for mirage-net 2.0.0

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Review by mato — COMMENTED** [review]
This looks reasonable, but I'd prefer that the magic number `14` (Ethernet header length) be turned into a symbolic constant of some kind.

Is this intended to be merged ASAP, or is it waiting on anything? (Sorry, lost track of the up/down stream PRs).

**Comment by hannesm** [comment]
@mato thanks for the review, I added an `ethernet_header_size` with the value 14 to not have to spread this over the codebase (and adjusted other mirage-net implementations with a similar patch).

in respect to merging: this requires mirage-net.2.0.0 which is (not yet) released. This PR can be merged at any point, but should not be released before mirage-net 2.0.0 hits opam-repository. I can take care of merging and releasing this PR if you're happy with the changes (including the most recent commit).

**Comment by mato** [comment]
@hannesm Thanks for adding `ethernet_header_size`. It is fine, _but_ will not accommodate 802.1Q VLANs. Are you still planning to support those? If yes, then we may need to think some more about how to do that, since on an 802.1Q tagged interface the MTU as reported by Solo5/the host will still be 1500, and the 802.1Q tag is technically considered part of the ethernet header.

**Comment by hannesm** [comment]
@mato I'm not sure I can follow. For 802.1q there are multiple possibilities:
- (1) the host system does 802.1q encapsulation/decapsulation (and provides the vlan interface instead of the tap device to the guest) -- in this case, the MTU should be 1496 (yes, I understand this is atm not the case in solo5) -- this is what my OS reports if I do `ifconfig vlan create ; ifconfig vlan0 vlan 42 vlandev tap0 ; ifconfig vlan0` (which would then be passed to `solo5-hvt`)
- (2) the guest system does 802.1q encapsulation/decapsulation. the MTU of the network interface is 1500. The vlan packets sent/received are 1514 in length. an upper layer (i.e. not https://github.com/mirage/ethernet but some vlan implementation using mirage-net-solo5) does vlan tagging by consuming 4 additional bytes from the mirage-net MTU.

Does that make sense? I'm mainly concerned about (2) in the following (since for (1) there is no responsibility of the guest to care about).


The `issue` is that the MTU always excludes the ethernet header, so the actual sent and received packets are a bit bigger. Now, whose responsibility is it to allocate the ethernet header bytes? And whose is it to fill it?

(a) In the current design, the mirage-net implementation (i.e. mirage-net-solo5) allocates the additional bytes, and the ethernet implementation (which is shared across mirage-net implementations) fills it.

(b) I can think of a different design where the mirage-net implementations report an MTU (or maximum packet size) that includes the ethernet header, and the ethernet implementation allocates and fills these additional bytes. Would that make more sense to you?

After more thinking, I like (b) more. This would entail that mirage-net-solo5 reports as mtu the interface MTU (from solo5_net_info) + ethernet_header_size.

**Comment by mato** [comment]
Summarizing a couple of hours of discussion with @hannesm on IRC:

802.1q is problematic, due to the fact that there is no way to reliably differentiate on a Linux/FreeBSD host between whether or not a network interface is "capable of sending and receiving long frames" or not.

So, taking 802.1q off the table, I'm fine with this PR as-is since I see no better solution right now.

**Pull request merged**
